[theme]
# This makes your "primary" buttons and progress bars Green
primaryColor = "#28a745"

# Background of the main app
backgroundColor = "#ffffff"

# Background of the sidebar and expanders
secondaryBackgroundColor = "#f0f2f6"

# Color of the text
textColor = "#262730"

# Font (optional)
font = "sans serif"

base = "light"